service:
    name: users

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true
    
# Add the serverless-webpack plugin
plugins:
- serverless-webpack
- serverless-offline

functions: 
    - ${file(./index.functions.yml)}
